controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use app\models\ContactForm;
use app\models\Provincias;
use app\models\Spots;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    public function actionMapapaises() {
        return $this->render('mapa-paises');
    }

    public function actionMapaprovinciasespana() {
        return $this->render('mapa-provincias-españa');
    }

    public function actionSpots() {
        return $this->render('spots');
    }

    public function actionConsultapais($nombrepais) {
        $eprovincias = new ActiveDataProvider([
            'query' => Provincias::find()->select('COUNT(idProvincia)nprovincias')->distinct()->where("idprovincia IN (SELECT idProvincia FROM provincias WHERE idautonomia IN(SELECT idAutonomia FROM autonomias  WHERE idpais=(SELECT idPais FROM paises  WHERE nombrePais='$nombrepais')))"),
        ]);
        $numerospotsprovincia = yii:: $app->db->createCommand("SELECT nombreProvincia,COUNT(*)nspots  FROM spots INNER JOIN (SELECT idMunicipio, idprovincia FROM municipios WHERE idprovincia IN(SELECT idProvincia FROM provincias WHERE idautonomia 
            IN(SELECT idAutonomia FROM autonomias  WHERE idpais=(SELECT idPais FROM paises  WHERE nombrePais='$nombrepais'))))c1 USING(idMunicipio) INNER JOIN (
  SELECT idProvincia, nombreProvincia FROM provincias WHERE idautonomia IN(SELECT idAutonomia FROM autonomias  WHERE idpais=(SELECT idPais FROM paises  WHERE nombrePais='$nombrepais'))
)c2 USING(idProvincia) GROUP BY c2.idProvincia")->queryAll();
        return $this->render('mapa-provincias-españa', [
                    "numerospotsprovincia" => $numerospotsprovincia,
                    "nombrepais" => $nombrepais,
                    "eprovincias" => $eprovincias,
        ]);
    }
    
     public function actionConsultaprovincia($nombreprovincia) {
        $spots = new SqlDataProvider([
            'sql'=>"select fecha,descripcion,posiblesPlanes,latitud,altitud from spots where idmunicipio IN (SELECT idMunicipio FROM municipios WHERE idprovincia IN(select idProvincia from provincias where nombreProvincia='$nombreprovincia'))",
        ]);
        
        return $this->render('spots', [
                   "spots"=>$spots,
            "nombreprovincia"=>$nombreprovincia,
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout() {
        return $this->render('about');
    }

}

views/site/_spots.php
<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

?>
<div class="tarjeta-spots">
    <h3>Estes Spot se encuentra en municipio</h3>
    <p>fecha <?=$model->fecha?>,descripcion<?=$model->descripcion?>,posiblesPlanes<?=$model->posiblesPlanes?>,latitud<?=$model->latitud?>,altitud<?=$model->altitud?></p>
</div>

views/site/_spotsmunicipio.php
<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

views/site/_tarjetaprovincias.php
<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */
use yii\helpers\Html;
use yii\widgets\ListView;
?>

<div class="tarjetaprovincias">
    <?php
            foreach ($numerospotsprovincia as $values) {
               
                $nomprovincia[] = ($values['nombreProvincia']);
                $numspots[] = intval($values['nspots']);
                echo $values['nombreProvincia']." tiene: ".$values['nspots']." Spots. <br>";
            }
            ?>
</div>

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var yii\web\View $this */
use yii\helpers\Html;
$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Bienvenido a Spots!</h1>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Estadisticas</h2>

                <p>Aqui podremos ver la puntuacion medias de los spots por paises, autonomias, provincias y municipios,
                    tambien podremos ver quien es el que mas spots tiene, cual es el mejor puntuado, cual es el mas visitado...</p>

                <p><a class="btn btn-outline-secondary" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Ir al mapa</h2>

                <p>Desde esta pestaña accederemos a un mapa, a la iz tendremos el numero de spots por paises que tenemos y en cuales se encuentran,
                    al llegar a la provincia deseada nos mostrara todos los spots que tiene esta agrupados por los municipios donde se encuentran,
                    pudiendo acceder a un mapa de la ubicacion proporcionado por las coordenadas.</p>

                <?= Html::a('Mapa', ['site/mapapaises'], ['class' => 'btn btn-success']) ?>
            </div>
            <div class="col-lg-4">
                <h2>Añadir un Spot</h2>

                <p>De alguna manera los usuarios podran crear spots introduciendo su dni y el municipio donde se encuentra.</p>

                <p><a class="btn btn-outline-secondary" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\LoginForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="offset-lg-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/mapa-paises.php
<?php
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

use yii\helpers\Html;
?>
<div class="">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Bienvenido a Spots!</h1>
    </div>

    <div class="body-content-paises">

        <div class="row">
            <div class="col-lg-2">
                <h2>Ir al mapa</h2>

                <p>Desde esta pestaña accederemos a un mapa, a la iz tendremos el numero de spots por paises que tenemos y en cuales se encuentran,
                    al llegar a la provincia deseada nos mostrara todos los spots que tiene esta agrupados por los municipios donde se encuentran,
                    pudiendo acceder a un mapa de la ubicacion proporcionado por las coordenadas.</p>
                <?= Html::a('Mapa 2', ['site/mapaprovinciasespana'], ['class' => 'btn btn-success']) ?>
            </div>
            <div class="col-lg-10 medidasmapas">
                <?= Html::img('@web/img/mapa-paises.jpg', ['alt' => 'Mapa Paises']) ?>
                <?= Html::a($text = null, ['site/consultapais','nombrepais' => 'España'], ['title'=>'España','class' => 'botonmapa btespaña']) ?>
                
            </div>

        </div>

    </div>
</div>

views/site/mapa-provincias-españa.php
<?php
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

use yii\widgets\ListView;
use yii\helpers\Html;
?>
<div class="">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Bienvenido a <?= $nombrepais ?>!</h1>
    </div>

    <div class="body-content-paises">

        <div class="row">
            <div class="col-lg-2">
                <h2>Provincia/Spots</h2>
                <?php
                echo ListView::widget([
                    'dataProvider' => $eprovincias,
                    'itemView' => '_tarjetaprovincias',
                    'layout' => " \n {items} \n\n{pager}",
                    'viewParams' => [
                        "numerospotsprovincia" => $numerospotsprovincia,
                        "nombrepais" => $nombrepais,
                    ],
                ]);
                ?>
            </div>
            <div class="col-lg-10 medidasmapas">
                <?= Html::img('@web/img/mapa-provincias-españa.jpg', ['alt' => 'Mapa Paises']) ?>
                <?= Html::a($text = null, ['site/consultaprovincia', 'nombreprovincia' => 'Cantabria'], ['title' => 'Cantabria', 'class' => 'botonmapa btcantabria']) ?>
                
            </div>

        </div>

    </div>
</div>

views/site/spots.php
<?php

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */
?>
<div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Estas denro de <?=$nombreprovincia?> </h1>
    </div>
<<h2>Elige tu Spot</h2>
<?php
var_dump($spots);
//echo ListView::widget([
//    'dataProvider' => $spots,,
//    'itemView' => '_spots',
//    'layout' => " \n {items} \n\n{pager}",
//    'viewParams' => [
//        "nombreprovincia" => $nombreprovincia,
//    ],
//]);
?>

views/site/spotsmunicipio.php
<?php

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */

?>
<br><br><br>
<?=
    ListView::widget([
        'dataProvider' => $datosciclista,
        'itemView' => '_spotsmunicipio',
        'layout' => " \n {items} \n\n{pager}",
        'viewParams' => ["etapasganadasciclista" => $etapasganadasciclista,
            "datosciclista" => $datosciclista,
            "puertosganadasciclista" => $puertosganadasciclista,
            "datospuertos" => $datospuertos,
            "datosetapa" => $datosetapa,
            "datosmaillot" => $datosmaillot,
            "maillotsllevados" => $maillotsllevados,
            
            
        ],
    ]);
    ?>
<iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d351.6239978531609!2d-<?=3?>.781516610166541!3d43.472727167738086!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses!2ses!4v1676649679941!5m2!1ses!2ses" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>